export enum ErrorType {
  /* Syntax Errors */
  AcornParseError,
  CallingNonFunctionValues,
  ConditionalExpressionTestNotBoolean,
  InconsistentTypeInConditionalExpression,
  IfAlternateNotABlockStatement,
  IfConsequentNotABlockStatement,
  IfTestNotBoolean,
  InvalidCallArguments,
  LogicalExpressionNotBoolean,
  LogicalExpressionNotSameType,
  MatchFailure,
  MissingIfAlternate,
  MissingSemicolon,
  MultipleDeclarations,
  MissingDeclarationExpression,
  InvalidNumberOfArguments,
  NonNumbersInArithmeticBinaryExpression,
  NonNumbersInArithmeticUnaryExpression,
  TrailingComma,
  UndefinedVariable,
  UseStrictEquality,
  UseStrictInequality,
  VariableRedeclaration
}
