export enum ErrorType {
  /* Syntax Errors */
  AcornParseError,
  CallingNonFunctionValues,
  ConditionalExpressionTestNotBoolean,
  ConditionalExpressionNotSame,
  FunctionValuesInBinaryExpression,
  IfAlternateNotABlockStatement,
  IfConsequentNotABlockStatement,
  IfTestNotBoolean,
  InvalidCallArguments,
  LogicalExpressionNotBoolean,
  LogicalExpressionNotSameType,
  MatchFailure,
  MissingIfAlternate,
  MissingSemicolon,
  MultipleDeclarations,
  MissingDeclarationExpression,
  TrailingComma,
  UndefinedVariable,
  UnaryExpressionArgumentNotNumber,
  UseStrictEquality,
  UseStrictInequality,
  VariableRedeclaration
}
